/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/common/AppButton.vue')['default']
    AppDatePicker: typeof import('./src/components/common/AppDatePicker.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppInputMask: typeof import('./src/components/common/AppInputMask.vue')['default']
    AppInputText: typeof import('./src/components/common/AppInputText.vue')['default']
    AppLink: typeof import('./src/components/common/AppLink.vue')['default']
    AppPassword: typeof import('./src/components/common/AppPassword.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    Contact: typeof import('./src/components/common/Contact.vue')['default']
    ContactModal: typeof import('./src/components/common/ContactModal.vue')['default']
    copy: typeof import('./src/components/common/ContactModal copy.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DataView: typeof import('primevue/dataview')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    InputMask: typeof import('primevue/inputmask')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./src/components/common/LoginForm.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Paginator: typeof import('primevue/paginator')['default']
    RegisterForm: typeof import('./src/components/common/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButton: typeof import('primevue/splitbutton')['default']
    Tag: typeof import('primevue/tag')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UpdateContactModal: typeof import('./src/components/common/UpdateContactModal.vue')['default']
  }
}
